CREATE TABLE EMPLOYEE19B004( 
Empno NUMBER NOT NULL CONSTRAINT EMPLOYEE19B004_Emplo_PK PRIMARY KEY, 
EName VARCHAR2(20)NOT NULL, 
Designation VARCHAR2(20)NOT NULL, 
qualification VARCHAR2(20), 
Joindate DATE DEFAULT SYSDATE 
)

CREATE TABLE GRADE19B004 ( 
Designation VARCHAR2(20)NOT NULL, 
Grade NUMBER(2) NOT NULL CONSTRAINT check_Grade CHECK (Grade Between 1 and 10), 
Totalposts  NUMBER NOT NULL, 
PostsAvailable NUMBER,  
CONSTRAINT PostsAvailable_ck CHECk(Totalposts <= PostsAvailable) 
)

CREATE TABLE PROJECT19B004 ( 
PID NUMBER(4) NOT NULL, 
Title VARCHAR2(20) NOT NULL, 
Client VARCHAR2(20) NOT NULL, 
Durations VARCHAR2(1) NOT NULL, 
Status VARCHAR2(20), CONSTRAINT ck_Status CHECK (Status IN ('New','In Progress','Complete')) 
)

CREATE TABLE TRAINING19B004 ( 
Tcode VARCHAR2(4) NOT NULL CONSTRAINT  TRAINING19B004_Tcode_PK  PRIMARY KEY,  
Title VARCHAR2(20) NOT NULL, 
StartDate DATE, 
EndDate DATE 
)


CREATE TABLE EMP_PROJECT19B004( 
Empno NUMBER(4)NOT NULL, CONSTRAINT EMP_PROJECT19B004_Empno_FK FOREIGN KEY(Empno) REFERENCES EMPLOYEE19B004(Empno),  
PID NUMBER (4)NOT NULL, 
PERFORMANCES VARCHAR2(4) NOT NULL, CONSTRAINT ck_PERFORMANCE CHECK (PERFORMANCES IN ('Excellent','Good','Fair','Bad','Poor')) 
)

CREATE TABLE EMP_TRAINING19B004 ( 
Empno NUMBER(4)NOT NULL,  
CONSTRAINT EMP_TRAINING19B004_Empno_FK FOREIGN KEY(Empno) REFERENCES EMPLOYEE19B004(Empno), 
Tcode VARCHAR2(4)NOT NULL, 
Attendance NUMBER(3) 
)

ALTER TABLE EMPLOYEE19B004 
ADD (Gender VARCHAR2(8) NOT NULL, CONSTRAINT check_Gender CHECK (Gender = 'Male' OR Gender = 'Female') 
)

ALTER TABLE TRAINING19B004
ADD (Instructor_Name VARCHAR2(20) NOT NULL 
)

ALTER TABLE GRADE19B004
ADD (Salary Number(10) NOT NULL 
)


