CREATE OR REPLACE TRIGGER EMPDATE19B004
BEFORE INSERT ON EMP19B004
FOR EACH ROW
DECLARE TEMP DATE;
BEGIN
 SELECT SYSDATE INTO TEMP FROM EMP19B004;
 IF (:NEW.HIREDATE IS NULL) 
 THEN
 :NEW.HIREDATE := TEMP;
 END IF;
END;
/ 

CREATE TRIGGER EMPBONUS19B004
BEFORE INSERT OR UPDATE ON EMP19B004 
FOR EACH ROW
BEGIN 
 :NEW.COMM := :NEW.SAL * 0.03; 
END; 
/
DROP TRIGGER EMPBONUS19B004;
