CREATE TABLE AUDITTABLE19B4A(
USER_NAME VARCHAR2(10) NOT NULL,
TABLE_NAME VARCHAR2(10) NOT NULL,
COLUMN_NAME VARCHAR2(10),
INS NUMBER(2),
UPD NUMBER(2) NOT NULL,
DEL NUMBER(2),
MAX_INS NUMBER(2),
MAX_UPD NUMBER(2) NOT NULL,
MAX_DEL NUMBER(2)
);
/
CREATE OR REPLACE TRIGGER AUDITEMP19B004A 
AFTER DELETE OR INSERT OR UPDATE ON EMP19B004 
FOR EACH ROW 
BEGIN 
IF DELETING THEN 
 	UPDATE 	AUDITTABLE19B4A 	SET 	DEL = DEL + 1 
 	WHERE 	USER_NAME = 'uit3' AND TABLE_NAME = 'emp19B004'  
 	AND   	COLUMN_NAME IS NULL; 
ELSIF INSERTING THEN 
 	UPDATE 	AUDITTABLE19B4A 	SET 	INS = INS + 1 
 	WHERE 	USER_NAME = 'uit3' AND TABLE_NAME = 'emp19B004' 
 	AND   	COLUMN_NAME IS NULL; 
ELSIF UPDATING('SAL') THEN 
 	UPDATE 	AUDITTABLE19B4A 	SET 	UPD = UPD + 1 
 	WHERE 	USER_NAME = 'uit3' AND TABLE_NAME = 'emp19B004'  
 	AND   	COLUMN_NAME = 'SAL'; 
ELSE 
 	UPDATE 	AUDITTABLE19B4A 	SET 	UPD = UPD + 1 
 	WHERE 	USER_NAME = 'uit3' AND TABLE_NAME = 'emp19B004' 
 	AND   	COLUMN_NAME IS NULL; 
END IF; 
END; 
/
--DROP TRIGGER AUDITEMP19B004A;

CREATE TABLE AUDITEPVALUE4A( 
USER_NAME VARCHAR2(20),
TIMESTAMP VARCHAR2(20),
ID NUMBER(15),
OLD_LAST_NAME VARCHAR2(20),
OLD_TITLE VARCHAR2(20),
NEW_TITLE VARCHAR2(20),
OLD_SALARY NUMBER(15),
NEW_SALARY NUMBER(15)
);


/


CREATE OR REPLACE TRIGGER AUDITEPVALUES4A
AFTER DELETE OR INSERT OR UPDATE ON EMP19B004 
FOR EACH ROW 
BEGIN 
INSERT INTO AUDITEPVALUE4A (USER_NAME, TIMESTAMP, ID, OLD_LAST_NAME, OLD_TITLE,NEW_TITLE, OLD_SALARY, NEW_SALARY) 
VALUES ('uit3', SYSDATE, :OLD.EMPNO, :OLD.ENAME, :OLD.JOB, :NEW.JOB, :OLD.SAL, :NEW.SAL);
END; 
/





CREATE OR REPLACE TRIGGER DERCOMM19B004SE
BEFORE INSERT OR UPDATE OF SAL ON EMP19B004 
FOR EACH ROW 
WHEN (NEW.JOB = 'SALESMAN') 
BEGIN 
      IF INSERTING THEN 	:NEW.COMM := 0; 
      ELSE  	/* UPDATE of salary */ 
 	IF :OLD.COMM IS NULL
  THEN :NEW.COMM := 0; 
 	ELSE 
 	 	:NEW.COMM := :OLD.COMM + (:NEW.SAL / :OLD.SAL);
    END IF;
    END IF;
  END; 
/


CREATE TABLE SCHEMAUDIT19B04
(
  DDL_DATE 		DATE,
  DDL_USER 		VARCHAR2(15),
  OBJECT_CREATED   VARCHAR2(15),
  OBJECT_NAME   VARCHAR2(15),
  DDL_OPERATION  	VARCHAR2(15)
);

CREATE OR REPLACE TRIGGER HRAUDITTR19B04 
AFTER DDL ON SCHEMA
BEGIN
  INSERT INTO SCHEMAUDIT19B04 VALUES 
  (
   SYSDATE,
   SYS_CONTEXT('USERENV','CURRENT_USER'),
   ORA_DICT_OBJ_TYPE, 
   ORA_DICT_OBJ_NAME,
   ORA_SYSEVENT
  );
END;
/
