--EXAMPLES
CREATE OR REPLACE TRIGGER SECURE_EMP19B004 
BEFORE INSERT ON EMP19B004
BEGIN 
  IF (TO_CHAR(SYSDATE, 'DY') IN ('SAT')) 
  OR (TO_CHAR(SYSDATE, 'HH24') NOT BETWEEN '08' AND '18')      
  THEN RAISE_APPLICATION_ERROR (-20000, 'You may only insert into EMP during normal hours.'); 
  END IF; 
END;
/

CREATE OR REPLACE TRIGGER SECURE_EMP19B004 
BEFORE INSERT OR UPDATE OR DELETE ON EMP19B004
BEGIN 
  IF (TO_CHAR(SYSDATE, 'DY') IN ('SAT')) 
  OR (TO_CHAR(SYSDATE, 'HH24') NOT BETWEEN '08' AND '18')     
  THEN   
  IF DELETING 
  THEN 
  RAISE_APPLICATION_ERROR (-20502, 'You may only delete from EMP during normal hours.'); 
  ELSIF INSERTING
  THEN 
  RAISE_APPLICATION_ERROR (-20500, 'You may only insert into EMP during normal hours.'); 
  ELSIF UPDATING('SAL') 
  THEN 
  RAISE_APPLICATION_ERROR (-20503, 'You may only update SAL during normal hours.'); 
  ELSE 
  RAISE_APPLICATION_ERROR (-20504, 'You may only update EMP during normal hours.'); 
  END IF; 
  END IF; 
END; 
/

CREATE TABLE ORDERS_AUDIT1_DELETE19B004
( ORDER_ID NUMBER(5),
 QUANTITY NUMBER(4),
 COST_PER_ITEM NUMBER(6,2),
 TOTAL_COST NUMBER(8,2),
 USERNAME VARCHAR(50),
 DATETRANS DATE,
 DETAIL VARCHAR(30)
);
CREATE TABLE AUDIT_TABLE19B004(
USER_NAME VARCHAR2(10) NOT NULL,
TABLE_NAME VARCHAR2(10) NOT NULL,
COLUMN_NAME VARCHAR2(10),
INS NUMBER(2),
UPD NUMBER(2) NOT NULL,
DEL NUMBER(2),
MAX_INS NUMBER(2),
MAX_UPD NUMBER(2) NOT NULL,
MAX_DEL NUMBER(2)
);




CREATE OR REPLACE TRIGGER CHECK_SALARY_COUNT19B004
AFTER UPDATE OF SAL ON EMP19B004
DECLARE 
  V_SALARY_CHANGES  NUMBER; 
  V_MAX_CHANGES     NUMBER; 
BEGIN 
SELECT UPD, MAX_UPD 
INTO V_SALARY_CHANGES, V_MAX_CHANGES 
FROM AUDIT_TABLE19B004
WHERE USER_NAME ='SCOTT'
AND TABLE_NAME = 'EMP19B004' 
AND COLUMN_NAME = 'SAL'; 
IF V_SALARY_CHANGES > V_MAX_CHANGES THEN 
    	RAISE_APPLICATION_ERROR (-20501, 'You may only make a maximum of ' 
 	|| TO_CHAR(V_MAX_CHANGES) || ' changes to the sal column'); 
ELSE UPDATE AUDIT_TABLE19B004 SET UPD = UPD+1 WHERE COLUMN_NAME='SAL';
END IF; END; 
/
--UPDATE EMP19B004 SET SAL=SAL+300 WHERE EMPNO = 7369;

--SELECT * FROM EMP19B004;
INSERT INTO AUDIT_TABLE19B004(USER_NAME,TABLE_NAME,COLUMN_NAME ,INS, UPD ,DEL ,MAX_INS, MAX_UPD, MAX_DEL)
VALUES('SCOTT','EMP19B004','SAL',NULL,1,NULL,NULL,5,NULL);



CREATE OR REPLACE TRIGGER ORDERS_AFTER_DELETE19B004
AFTER DELETE
   ON ORDERS_AUDIT1_DELETE19B004
   FOR EACH ROW

DECLARE
   V_USERNAME VARCHAR2(10);
DETAILS VARCHAR(30);

BEGIN
DETAILS:='record has been deleted'|| TO_CHAR(:OLD.ORDER_ID);

   -- Find username of person performing the INSERT into the table
   SELECT USER INTO V_USERNAME
   FROM DUAL;
   -- Insert record into audit table
   INSERT INTO ORDERS_AUDIT1_DELETE19B004
   ( ORDER_ID,
    QUANTITY,
    COST_PER_ITEM,
    TOTAL_COST,
    USERNAME,DATETRANS,DETAIL )
   VALUES
   (:OLD.ORDER_ID,
    :OLD.QUANTITY,
    :OLD.COST_PER_ITEM,
    :OLD.TOTAL_COST,
    V_USERNAME,SYSDATE,DETAILS );
END;
/