Select Suppliers.ContactName, count(Products.ProductID) As NumberofProducts from Suppliers
Inner Join Products On Suppliers.SupplierID = Products.SupplierID
Group By Suppliers.ContactName;
SELECT * FROM PRODUCTS;
SELECT SUPPLIERS.ContactName, COUNT(PRODUCTS.PRODUCTID) As NumberofProducts FROM SUPPLIERS 
INNER JOIN PRODUCTS ON SUPPLIERS.SUPPLIERID = PRODUCTS.SUPPLIERID;

SELECT SUPPLIERS.CONTACTNAME, COUNT(PRODUCTS.PRODUCTID) AS NO_OF_PRODUCTS FROM SUPPLIERS 
INNER JOIN PRODUCTS ON SUPPLIERS.SUPPLIERID = PRODUCTS.SUPPLIERID GROUP BY SUPPLIERS.CONTACTNAME;

Select Suppliers.ContactName, count(Products.ProductID) As NumberofProducts
from Suppliers Inner Join Products On Suppliers.SupplierID = Products.SupplierID
Group By Suppliers.ContactName having count(Products.ProductID) > 4;

SELECT REGION.REGIONDESCRIPTION AS REGIONNAME, COUNT(EMPLOYEES.EMPLOYEEID) AS NO_OF_EMPLOYEES FROM REGION
INNER JOIN TERRITORIES ON TERRITORIES.REGIONID = REGION.REGIONID 
INNER JOIN EMPLOYEETERRITORIES ON EMPLOYEETERRITORIES.TERRITORYID = TERRITORIES.TERRITORYID 
INNER JOIN EMPLOYEES ON EMPLOYEES.EMPLOYEEID = EMPLOYEETERRITORIES.EMPLOYEEID 
GROUP BY REGION.REGIONDESCRIPTION;

SELECT * FROM EMPLOYEES;

SELECT REGION.REGIONDESCRIPTION AS REGIONNAME,COUNT(EMPLOYEES.EMPLOYEEID) AS NO_OF_EMPLOYEES FROM REGION 
INNER JOIN TERRITORIES ON TERRITORIES.REGIONID = REGION.REGIONID 
INNER JOIN EMPLOYEETERRITORIES ON EMPLOYEETERRITORIES.TERRITORYID = TERRITORIES.TERRITORYID
INNER JOIN EMPLOYEES ON EMPLOYEES.EMPLOYEEID = EMPLOYEETERRITORIES.EMPLOYEEID 
GROUP BY REGION.REGIONDESCRIPTION;

SELECT CONTACTNAME , ORDERS.ORDERID FROM CUSTOMERS 
LEFT JOIN ORDERS ON ORDERS.CUSTOMERID = CUSTOMERS.CUSTOMERID WHERE ORDERS.ORDERID IS NULL;

select regiondescription, count(regiondescription) from (
Select Region.RegionDescription
from Region Inner Join Territories On Region.RegionID = Territories.RegionID
Inner Join EmployeeTerritories 
On Territories.TerritoryID = EmployeeTerritories.TerritoryID
Inner Join Employees On EmployeeTerritories.EmployeeID= Employees.EmployeeID
Group By Region.RegionDescription, employeeterritories.employeeid) 
Group By Regiondescription;

SELECT REGION.REGIONDESCRIPTION AS REGIONNAME,COUNT(EMPLOYEES.EMPLOYEEID) AS NO_OF_EMPLOYEES FROM REGION 
INNER JOIN TERRITORIES ON TERRITORIES.REGIONID = REGION.REGIONID INNER JOIN EMPLOYEETERRITORIES ON EMPLOYEETERRITORIES.TERRITORYID = TERRITORIES.TERRITORYID
INNER JOIN EMPLOYEES ON EMPLOYEES.EMPLOYEEID = EMPLOYEETERRITORIES.EMPLOYEEID GROUP BY REGION.REGIONDESCRIPTION;

SELECT "EMPLOYEENAME" FROM (SELECT FIRSTNAME || ' ' || LASTNAME AS "EMPLOYEENAME", COUNT(ORDERID) FROM EMPLOYEES 
INNER JOIN ORDERS ON EMPLOYEES.EMPLOYEEID = ORDERS.EMPLOYEEID GROUP BY FIRSTNAME || ' ' || LASTNAME 
ORDER BY COUNT(ORDERID) DESC) WHERE ROWNUM <= 3;

Select od.orderid, p.productname,ca.categoryname 
from OrderDetails od inner join Products p on od.productid=p.productid inner join Orders o 
on od.orderid=o.orderid inner join Categories ca on p.categoryid=ca.categoryid 
where ca.categoryname not in ('Meat/Poultry','Dairy Products') ;

select o.orderid,sum((od.unitprice*od.quantity)-discount) as "Total Price" 
from Orders o inner join Orderdetails od on o.orderid=od.orderid 
group by o.orderid;

select c.country, count(*) from Customers c group by c.country order by count(*) desc;

SELECT COUNTRY FROM (SELECT COUNT(CUST.COUNTRY) AS C , CUSTOMERS.COUNTRY FROM CUSTOMERS CUST 
JOIN CUSTOMERS ON CUST.COUNTRY = CUSTOMERS.COUNTRY 
GROUP BY CUSTOMERS.COUNTRY ORDER BY C DESC) WHERE ROWNUM = 1;
