CREATE TABLE EMPLOYEE19B004( 
Empno NUMBER(3) NOT NULL CONSTRAINT EMPLOYEE19B004_Emplo_PK PRIMARY KEY, 
EName VARCHAR2(20)NOT NULL, 
Designation VARCHAR2(20)NOT NULL, 
qualification VARCHAR2(20), 
Joindate DATE DEFAULT SYSDATE, 
Gender VARCHAR(8) NOT NULL, 
CONSTRAINT ck_Gender CHECK (Gender = 'MALE' OR Gender = 'FEMALE') 
);

CREATE TABLE GRADE19B004 ( 
Designation VARCHAR2(20)NOT NULL, 
Grade NUMBER(2) NOT NULL CONSTRAINT check_Grade CHECK (Grade Between 1 and 10), 
Totalposts  NUMBER(4) NOT NULL, 
PostsAvailable NUMBER(4),  
CONSTRAINT PostsAvailable_ck CHECk(Totalposts <= PostsAvailable) 
);

CREATE TABLE PROJECT19B004 ( 
PID NUMBER(4) NOT NULL CONSTRAINT PROJECT19B004_PID_PK PRIMARY KEY, 
Title VARCHAR2(20) NOT NULL, 
Client VARCHAR2(20) NOT NULL, 
Durations VARCHAR2(1) NOT NULL, 
Status VARCHAR2(20) CONSTRAINT ck_Status CHECK (Status IN ('New','In Progress','Complete')) 
);

CREATE TABLE TRAINING19B004 ( 
Tcode VARCHAR2(4) NOT NULL CONSTRAINT  TRAINING19B004_Tcode_PK  PRIMARY KEY,  
Title VARCHAR2(20) NOT NULL, 
StartDate DATE, 
EndDate DATE 
);

CREATE TABLE EMP_PROJECT19B004( 
Empno NUMBER(4)NOT NULL,   
PID NUMBER (4)NOT NULL, 
PERFORMANCES VARCHAR2(4) NOT NULL, CONSTRAINT ck_PERFORMANCE CHECK (PERFORMANCES IN ('Excellent','Good','Fair','Bad','Poor')), 
CONSTRAINT EMP_PROJECT19B004_Empno_FK FOREIGN KEY(Empno) REFERENCES EMPLOYEE19B004(Empno), 
CONSTRAINT EMP_PROJECT19B004_PID_FK FOREIGN KEY (PID) REFERENCES PROJECT19B004(PID) 
 
);

CREATE TABLE EMP_TRAINING19B004 ( 
Empno NUMBER(4)NOT NULL,  
Tcode VARCHAR2(4)NOT NULL, 
Attendance NUMBER(3), 
CONSTRAINT EMP_TRAINING19B004_Empno_FK FOREIGN KEY (Empno) REFERENCES EMPLOYEE19B004 (Empno), 
CONSTRAINT EMP_TRAINING19B004_Tcode_FK FOREIGN KEY (Tcode) REFERENCES TRAINING19B004 (Tcode) 
);

INSERT INTO EMPLOYEE19B004 (Empno,EName,Designation,qualification,Gender) 
VALUES(101,'ADNAN','STUDENT','Undergraduate','MALE');

INSERT INTO EMPLOYEE19B004 (Empno,EName,Designation,qualification,Gender) 
VALUES(102,'ANABIYA','STUDENT','Undergraduate','FEMALE');

CREATE SEQUENCE EMPLOYEE19B004_EMPNO 
INCREMENT BY 1 
MAXVALUE 10000;


CREATE INDEX EMPLOYEE19B004_NAME ON EMPLOYEE19B004(EName);

CREATE INDEX EMPLOYEE19B004_DESISGNATION ON EMPLOYEE19B004(Designation);

CREATE INDEX TRAINING19B004_IDX ON TRAINING19B004(SUBSTR(Title,1,10));

CREATE BITMAP INDEX EMPLOYEE19B004_GENDER_IDX ON EMPLOYEE19B004(Gender);

CREATE BITMAP INDEX EMP_PROJECT19B004_PERFORMANCE ON EMP_PROJECT19B004(PERFORMANCES);

